# Generated by Django 5.2 on 2025-05-26 23:40

import ckeditor_uploader.fields
import content.models
import django.db.models.deletion
import django.utils.timezone
import taggit_autosuggest.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                ('meta_keywords', models.CharField(blank=True, default='', max_length=255, verbose_name='Meta keywords')),
                ('meta_description', models.CharField(blank=True, default='', max_length=255, verbose_name='Meta description')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('hidden', models.BooleanField(default=False, verbose_name='Is hidden')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PostTaggedItem',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('taggit.taggeditem',),
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('taggit.tag',),
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Title')),
                ('url', models.CharField(db_index=True, default='', editable=False, max_length=255, verbose_name='Path')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('template', models.CharField(choices=[('content_view', 'View single page'), ('content_list', 'List pages')], default='content_view', max_length=100, verbose_name='Template')),
                ('meta_keywords', models.CharField(blank=True, default='', max_length=255, verbose_name='Meta keywords')),
                ('meta_description', models.CharField(blank=True, default='', max_length=255, verbose_name='Meta description')),
                ('enabled', models.BooleanField(db_index=True, default=True, verbose_name='Enabled')),
                ('hidden', models.BooleanField(db_index=True, default=False, verbose_name='Is hidden')),
                ('type', models.CharField(choices=[('page', 'Page'), ('gallery', 'Gallery')], db_index=True, default='page', max_length=64)),
                ('image', models.ImageField(blank=True, upload_to='content/%Y/%m/%d')),
                ('date_published', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Date published')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Content')),
                ('comments', models.BooleanField(default=False, verbose_name='Allow comments')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], default='en', max_length=5, verbose_name='Language')),
                ('json', models.JSONField(default=content.models.default_json, editable=False, verbose_name='Json content')),
                ('rating', models.IntegerField(default=0, verbose_name='Rating')),
                ('show_count', models.IntegerField(default=0, verbose_name='Show count')),
                ('view_count', models.IntegerField(default=0, verbose_name='View count')),
                ('category', models.ManyToManyField(blank=True, to='content.category', verbose_name='Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_user', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit_autosuggest.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='content.PostTaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Content',
            },
        ),
    ]
