# Generated by Django 5.2 on 2025-06-23 11:55

import django.db.models.deletion
import django.utils.timezone
import taggit_autosuggest.managers
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTaggedItem',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('taggit.taggeditem',),
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('taggit.tag',),
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('sib_order', models.PositiveIntegerField(default=0, verbose_name='Sibling order')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Title')),
                ('url', models.CharField(db_index=True, default='', editable=False, max_length=255, verbose_name='Path')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('template', models.CharField(choices=[('content_view', 'View single page'), ('content_list', 'List pages')], default='content_view', max_length=100, verbose_name='Template')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], default='en', max_length=5, verbose_name='Language')),
                ('type', models.CharField(choices=[('html', 'HTML'), ('md', 'Markdown'), ('plain', 'Plain text')], db_index=True, default='html', max_length=64)),
                ('date_published', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Date published')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('allow_comments', models.BooleanField(default=False, verbose_name='Allow comments')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, verbose_name='Enabled')),
                ('is_hidden', models.BooleanField(db_index=True, default=False, verbose_name='Is hidden')),
                ('pass_access', models.CharField(blank=True, max_length=64, null=True, verbose_name='Password')),
                ('json', models.JSONField(default=dict, editable=False, verbose_name='Json content')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.content', verbose_name='Parent content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_user', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit_autosuggest.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='content.PostTaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Content',
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('file', models.FileField(upload_to='content/%Y/%m/%d', verbose_name='File')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='content.content')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
    ]
